packages:
  - "packages/*"

nodeLinker: hoisted
minimumReleaseAge: 7200
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 525600
trustPolicyExclude:
  - rollup

allowBuilds:
  "@parcel/watcher": false
  "@vscode/vsce-sign": false
  cypress: true
  core-js: true
  esbuild: true
  keytar: false
  protobufjs: false
  vue-demi: false
